-- 1. Create Profiles Table (Public User Data)
-- This table mirrors the auth.users table but holds public info like content, avatar, etc.
create table public.profiles (
  id uuid not null references auth.users on delete cascade,
  full_name text null,
  avatar_url text null,
  website text null,
  role text default 'buyer', -- 'buyer', 'agent', 'admin'
  primary key (id)
);

-- Turn on Row Level Security
alter table public.profiles enable row level security;

-- Create policies for profiles
create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- 2. Create Properties Table
create table public.properties (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text null,
  price numeric not null,
  location text not null, 
  address text not null,
  beds integer null,
  baths numeric null,
  sqft integer null,
  type text null, -- 'Sale', 'Rent'
  image text null,
  features text[] null, -- Array of strings
  agent_id uuid references public.profiles(id)
);

-- Turn on Row Level Security
alter table public.properties enable row level security;

-- Create policies for properties
create policy "Properties are viewable by everyone."
  on properties for select
  using ( true );

-- (Optional) Only agents can insert/update properties
-- For now, we allow authenticated users to insert for demo purposes
create policy "Authenticated users can create properties."
  on properties for insert
  with check ( auth.role() = 'authenticated' );

-- 3. Create Favorites Table (User Saved Homes)
create table public.favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  property_id bigint references public.properties(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, property_id)
);

alter table public.favorites enable row level security;

create policy "Users can view their own favorites."
  on favorites for select
  using ( auth.uid() = user_id );

create policy "Users can add favorites."
  on favorites for insert
  with check ( auth.uid() = user_id );

create policy "Users can remove their own favorites."
  on favorites for delete
  using ( auth.uid() = user_id );

-- 4. SEED DATA (from mock data)
insert into public.properties (title, location, address, price, beds, baths, sqft, type, image, description, features)
values
(
  'Modern Luxury Villa',
  'Beverly Hills, CA',
  '123 Palm Ave, Beverly Hills, CA 90210',
  4500000,
  5,
  4,
  4200,
  'Sale',
  'https://images.unsplash.com/photo-1613490493576-7fde63acd811?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80',
  'Experience the epitome of luxury living in this stunning modern villa.',
  ARRAY['Smart Home System', 'Swimming Pool', 'Home Theater']
),
(
  'Downtown Penthouse',
  'New York, NY',
  '555 Broadway, New York, NY 10012',
  2800000,
  3,
  2,
  2100,
  'Sale',
  'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80',
  'Stunning penthouse in the heart of SoHo.',
  ARRAY['City Views', 'Private Terrace', 'Doorman']
),
(
  'Cozy Beachfront Cottage',
  'Miami, FL',
  '789 Ocean Dr, Miami Beach, FL 33139',
  1200000,
  4,
  3,
  2800,
  'Sale',
  'https://images.unsplash.com/photo-1600596542815-2a4d9f0152ba?ixlib=rb-4.0.3&auto=format&fit=crop&w=1600&q=80',
  'Direct beach access and stunning ocean views.',
  ARRAY['Beach Access', 'Ocean View', 'Wraparound Porch']
);

-- 5. Trigger to automatically create profile on signup
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data ->> 'full_name', new.raw_user_meta_data ->> 'avatar_url');
  return new;
end;
$$;

-- trigger the function every time a user is created
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();
